const coffeeMenu = [
  {
    id: '1',
    title: 'Espresso',
    description: 'A strong, concentrated coffee made by forcing hot water through finely-ground coffee beans.',
    image: require('../assets/images/image.png'),
    roasted: 'Dark Roasted',
    imagelink_square: require('../assets/images/image.png'),
    imagelink_portrait: require('../assets/images/image.png'),
    ingredients: 'Coffee Beans',
    special_ingredient: 'None',
    prices: [
      { size: 'S', price: '1.50', currency: '$' },
      { size: 'M', price: '2.50', currency: '$' },
      { size: 'L', price: '3.00', currency: '$' }
    ],
    average_rating: 4.5,
    ratings_count: '10,582',
    favourite: false,
    type: 'Coffee',
    index: 1,
  },
  {
    id: '2',
    title: 'Cappuccino',
    description: 'A frothy coffee made with equal parts espresso, steamed milk, and foamed milk.',
    image: require('../assets/images/image1.png'),
    roasted: 'Medium Roasted',
    imagelink_square: require('../assets/images/image1.png'),
    imagelink_portrait: require('../assets/images/image1.png'),
    ingredients: 'Milk',
    special_ingredient: 'Foamed Milk',
    prices: [
      { size: 'S', price: '2.00', currency: '$' },
      { size: 'M', price: '3.50', currency: '$' },
      { size: 'L', price: '4.50', currency: '$' }
    ],
    average_rating: 4.6,
    ratings_count: '7,320',
    favourite: false,
    type: 'Coffee',
    index: 2,
  },
  {
    id: '3',
    title: 'Latte',
    description: 'A smooth coffee with espresso and steamed milk, topped with a small layer of foam.',
    image: require('../assets/images/image2.png'),
    roasted: 'Medium Roasted',
    imagelink_square: require('../assets/images/image2.png'),
    imagelink_portrait: require('../assets/images/image2.png'),
    ingredients: 'Milk',
    special_ingredient: 'Steamed Milk',
    prices: [
      { size: 'S', price: '1.38', currency: '$' },
      { size: 'M', price: '3.15', currency: '$' },
      { size: 'L', price: '4.29', currency: '$' }
    ],
    average_rating: 4.7,
    ratings_count: '6,879',
    favourite: false,
    type: 'Coffee',
    index: 3,
  },
  {
    id: '4',
    title: 'Macchiato',
    description: 'A bold espresso topped with a small amount of foamed milk.',
    image: require('../assets/images/image3.png'),
    roasted: 'Dark Roasted',
    imagelink_square: require('../assets/images/image3.png'),
    imagelink_portrait: require('../assets/images/image3.png'),
    ingredients: 'Milk',
    special_ingredient: 'Foamed Milk',
    prices: [
      { size: 'S', price: '2.00', currency: '$' },
      { size: 'M', price: '4.00', currency: '$' },
      { size: 'L', price: '4.75', currency: '$' }
    ],
    average_rating: 4.8,
    ratings_count: '5,200',
    favourite: true,
    type: 'Coffee',
    index: 4,
  },
  {
    id: '5',
    title: 'Mocha',
    description: 'A chocolate-flavored coffee made with espresso, steamed milk, and cocoa powder.',
    image: require('../assets/images/image4.png'),
    roasted: 'Medium Roasted',
    imagelink_square: require('../assets/images/image4.png'),
    imagelink_portrait: require('../assets/images/image4.png'),
    ingredients: 'Milk, Cocoa Powder',
    special_ingredient: 'Chocolate Syrup',
    prices: [
      { size: 'S', price: '2.25', currency: '$' },
      { size: 'M', price: '3.75', currency: '$' },
      { size: 'L', price: '5.25', currency: '$' }
    ],
    average_rating: 4.9,
    ratings_count: '4,890',
    favourite: true,
    type: 'Coffee',
    index: 5,
  },
  {
    id: '6',
    title: 'Flat White',
    description: 'A creamy coffee made with a shot of espresso and steamed milk with a thin layer of foam.',
    image: require('../assets/images/image.png'),
    roasted: 'Light Roasted',
    imagelink_square: require('../assets/images/image.png'),
    imagelink_portrait: require('../assets/images/image.png'),
    ingredients: 'Milk',
    special_ingredient: 'None',
    prices: [
      { size: 'S', price: '2.00', currency: '$' },
      { size: 'M', price: '3.00', currency: '$' },
      { size: 'L', price: '4.00', currency: '$' }
    ],
    average_rating: 4.3,
    ratings_count: '3,578',
    favourite: false,
    type: 'Coffee',
    index: 6,
  },
  {
    id: '7',
    title: 'Americano',
    description: 'A rich and smooth coffee made by adding hot water to espresso.',
    image: require('../assets/images/image1.png'),
    roasted: 'Dark Roasted',
    imagelink_square: require('../assets/images/image1.png'),
    imagelink_portrait: require('../assets/images/image1.png'),
    ingredients: 'Coffee Beans, Water',
    special_ingredient: 'None',
    prices: [
      { size: 'S', price: '1.75', currency: '$' },
      { size: 'M', price: '2.50', currency: '$' },
      { size: 'L', price: '3.50', currency: '$' }
    ],
    average_rating: 4.1,
    ratings_count: '2,934',
    favourite: false,
    type: 'Coffee',
    index: 7,
  },
  {
    id: '8',
    title: 'Affogato',
    description: 'Hot espresso poured over vanilla ice cream for a delicious dessert coffee.',
    image: require('../assets/images/image2.png'),
    roasted: 'Medium Roasted',
    imagelink_square: require('../assets/images/image2.png'),
    imagelink_portrait: require('../assets/images/image2.png'),
    ingredients: 'Vanilla Ice Cream',
    special_ingredient: 'Espresso',
    prices: [
      { size: 'S', price: '3.50', currency: '$' },
      { size: 'M', price: '5.00', currency: '$' },
      { size: 'L', price: '6.00', currency: '$' }
    ],
    average_rating: 4.8,
    ratings_count: '1,204',
    favourite: true,
    type: 'Coffee',
    index: 8,
  },
  {
    id: '9',
    title: 'Cortado',
    description: 'A balanced coffee made with equal parts espresso and warm milk.',
    image: require('../assets/images/image3.png'),
    roasted: 'Dark Roasted',
    imagelink_square: require('../assets/images/image3.png'),
    imagelink_portrait: require('../assets/images/image3.png'),
    ingredients: 'Milk',
    special_ingredient: 'None',
    prices: [
      { size: 'S', price: '2.50', currency: '$' },
      { size: 'M', price: '3.75', currency: '$' },
      { size: 'L', price: '4.20', currency: '$' }
    ],
    average_rating: 4.7,
    ratings_count: '1,987',
    favourite: false,
    type: 'Coffee',
    index: 9,
  },
  {
    id: '10',
    title: 'Irish Coffee',
    description: 'A coffee with whiskey, sugar, and cream, topped with whipped cream.',
    image: require('../assets/images/image4.png'),
    roasted: 'Medium Roasted',
    imagelink_square: require('../assets/images/image4.png'),
    imagelink_portrait: require('../assets/images/image4.png'),
    ingredients: 'Whiskey, Sugar, Cream',
    special_ingredient: 'Whipped Cream',
    prices: [
      { size: 'S', price: '4.00', currency: '$' },
      { size: 'M', price: '5.50', currency: '$' },
      { size: 'L', price: '7.00', currency: '$' }
    ],
    average_rating: 4.9,
    ratings_count: '789',
    favourite: true,
    type: 'Coffee',
    index: 10,
  },
  {
    id: '11',
    title: 'Cold Brew',
    description: 'Smooth and cold coffee steeped in water for hours.',
    image: require('../assets/images/image.png'),
    roasted: 'Medium Roasted',
    imagelink_square: require('../assets/images/image.png'),
    imagelink_portrait: require('../assets/images/image.png'),
    ingredients: 'Coffee Beans, Water',
    special_ingredient: 'None',
    prices: [
      { size: 'S', price: '2.50', currency: '$' },
      { size: 'M', price: '3.50', currency: '$' },
      { size: 'L', price: '4.50', currency: '$' }
    ],
    average_rating: 4.2,
    ratings_count: '5,010',
    favourite: false,
    type: 'Coffee',
    index: 11,
  },
  {
    id: '12',
    title: 'Nitro Cold Brew',
    description: 'Cold brew coffee infused with nitrogen for a smoother texture.',
    image: require('../assets/images/image1.png'),
    roasted: 'Medium Roasted',
    imagelink_square: require('../assets/images/image1.png'),
    imagelink_portrait: require('../assets/images/image1.png'),
    ingredients: 'Coffee Beans, Water',
    special_ingredient: 'Nitrogen',
    prices: [
      { size: 'S', price: '3.00', currency: '$' },
      { size: 'M', price: '4.00', currency: '$' },
      { size: 'L', price: '5.00', currency: '$' }
    ],
    average_rating: 4.4,
    ratings_count: '6,250',
    favourite: true,
    type: 'Coffee',
    index: 12,
  },
  {
    id: '13',
    title: 'Turkish Coffee',
    description: 'Strong and thick coffee made by simmering fine coffee grounds with sugar.',
    image: require('../assets/images/image2.png'),
    roasted: 'Dark Roasted',
    imagelink_square: require('../assets/images/image2.png'),
    imagelink_portrait: require('../assets/images/image2.png'),
    ingredients: 'Coffee Grounds, Sugar',
    special_ingredient: 'None',
    prices: [
      { size: 'S', price: '2.50', currency: '$' },
      { size: 'M', price: '3.50', currency: '$' },
      { size: 'L', price: '4.50', currency: '$' }
    ],
    average_rating: 4.7,
    ratings_count: '2,540',
    favourite: false,
    type: 'Coffee',
    index: 13,
  },
  {
    id: '14',
    title: 'Doppio',
    description: 'A double shot of espresso with a rich and strong flavor.',
    image: require('../assets/images/image3.png'),
    roasted: 'Dark Roasted',
    imagelink_square: require('../assets/images/image3.png'),
    imagelink_portrait: require('../assets/images/image3.png'),
    ingredients: 'Coffee Beans',
    special_ingredient: 'None',
    prices: [
      { size: 'S', price: '2.00', currency: '$' },
      { size: 'M', price: '3.00', currency: '$' },
      { size: 'L', price: '4.00', currency: '$' }
    ],
    average_rating: 4.5,
    ratings_count: '1,900',
    favourite: false,
    type: 'Coffee',
    index: 14,
  },
  {
    id: '15',
    title: 'Ristretto',
    description: 'A shorter and more intense shot of espresso.',
    image: require('../assets/images/image4.png'),
    roasted: 'Dark Roasted',
    imagelink_square: require('../assets/images/image4.png'),
    imagelink_portrait: require('../assets/images/image4.png'),
    ingredients: 'Coffee Beans',
    special_ingredient: 'None',
    prices: [
      { size: 'S', price: '1.50', currency: '$' },
      { size: 'M', price: '2.50', currency: '$' },
      { size: 'L', price: '3.50', currency: '$' }
    ],
    average_rating: 4.6,
    ratings_count: '1,600',
    favourite: false,
    type: 'Coffee',
    index: 15,
  },
  {
    id: '16',
    title: 'Vienna Coffee',
    description: 'A rich coffee topped with whipped cream.',
    image: require('../assets/images/image.png'),
    roasted: 'Medium Roasted',
    imagelink_square: require('../assets/images/image.png'),
    imagelink_portrait: require('../assets/images/image.png'),
    ingredients: 'Whipped Cream',
    special_ingredient: 'None',
    prices: [
      { size: 'S', price: '3.00', currency: '$' },
      { size: 'M', price: '4.50', currency: '$' },
      { size: 'L', price: '5.50', currency: '$' }
    ],
    average_rating: 4.9,
    ratings_count: '2,100',
    favourite: true,
    type: 'Coffee',
    index: 16,
  },
  {
    id: '17',
    title: 'Lungo',
    description: 'A long espresso shot with more water, creating a larger and milder drink.',
    image: require('../assets/images/image1.png'),
    roasted: 'Dark Roasted',
    imagelink_square: require('../assets/images/image1.png'),
    imagelink_portrait: require('../assets/images/image1.png'),
    ingredients: 'Coffee Beans, Water',
    special_ingredient: 'None',
    prices: [
      { size: 'S', price: '2.25', currency: '$' },
      { size: 'M', price: '3.50', currency: '$' },
      { size: 'L', price: '4.75', currency: '$' }
    ],
    average_rating: 4.4,
    ratings_count: '1,789',
    favourite: true,
    type: 'Coffee',
    index: 17,
  },
  {
    id: '18',
    title: 'Iced Latte',
    description: 'A refreshing cold coffee made with espresso, cold milk, and ice.',
    image: require('../assets/images/image2.png'),
    roasted: 'Medium Roasted',
    imagelink_square: require('../assets/images/image2.png'),
    imagelink_portrait: require('../assets/images/image2.png'),
    ingredients: 'Milk, Ice',
    special_ingredient: 'None',
    prices: [
      { size: 'S', price: '2.00', currency: '$' },
      { size: 'M', price: '3.50', currency: '$' },
      { size: 'L', price: '4.50', currency: '$' }
    ],
    average_rating: 4.6,
    ratings_count: '5,940',
    favourite: false,
    type: 'Coffee',
    index: 18,
  },
  {
    id: '19',
    title: 'Iced Mocha',
    description: 'A cold coffee made with espresso, cold milk, chocolate syrup, and ice.',
    image: require('../assets/images/image3.png'),
    roasted: 'Medium Roasted',
    imagelink_square: require('../assets/images/image3.png'),
    imagelink_portrait: require('../assets/images/image3.png'),
    ingredients: 'Milk, Cocoa Powder, Ice',
    special_ingredient: 'Chocolate Syrup',
    prices: [
      { size: 'S', price: '2.75', currency: '$' },
      { size: 'M', price: '4.00', currency: '$' },
      { size: 'L', price: '5.50', currency: '$' }
    ],
    average_rating: 4.7,
    ratings_count: '3,745',
    favourite: true,
    type: 'Coffee',
    index: 19,
  },
  {
    id: '20',
    title: 'Iced Caramel Macchiato',
    description: 'A cold coffee with espresso, milk, caramel syrup, and ice.',
    image: require('../assets/images/image4.png'),
    roasted: 'Medium Roasted',
    imagelink_square: require('../assets/images/image4.png'),
    imagelink_portrait: require('../assets/images/image4.png'),
    ingredients: 'Milk, Caramel Syrup, Ice',
    special_ingredient: 'Caramel Drizzle',
    prices: [
      { size: 'S', price: '3.25', currency: '$' },
      { size: 'M', price: '4.50', currency: '$' },
      { size: 'L', price: '5.75', currency: '$' }
    ],
    average_rating: 4.8,
    ratings_count: '4,320',
    favourite: true,
    type: 'Coffee',
    index: 20,
  }
];

export default coffeeMenu;